name: Build And Release
# last update,i tried 7 to 11 : 50 for4 hr 50 min.but successful at all


on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      release_note:
        description: 'Optional note for the release body'
        required: false
        default: ''

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install markdown-convert
        run: pip install markdown-convert

      - name: Convert to PDF
        run: markdown-convert ./book.md --out=./demo.pdf

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MD2PDF
          path: ./demo.pdf

      - name: Set BUILD_DATE environment variable
        run: echo "BUILD_DATE=$(date --rfc-3339=date)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Date-${{ env.BUILD_DATE }}
          name: Release ${{ github.ref_name }}
          body: |
            PDF Release for: ${{ env.BUILD_DATE }}
            ${{ github.event.inputs.release_note }}
          draft: false
          prerelease: false
          files: ./demo.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
